# Generated by Django 3.1.7 on 2021-04-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.Product'),
        ),
    ]
