# Generated by Django 3.1.7 on 2021-04-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210411_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
