# Generated by Django 3.1.7 on 2021-04-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20210411_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product', to='ecom.Product'),
        ),
    ]
