# Generated by Django 3.1.7 on 2021-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_quantity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quan',
            field=models.ManyToManyField(related_name='quan', to='ecom.Quantity'),
        ),
    ]
